package com.vyako.smartfactory.main.models.database.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "DEMO".
 */
@Entity
public class Demo {

    @Id(autoincrement = true)
    private Long id;
    private String coloum1;
    private String coloum2;
    private String coloum3;
    private String coloum4;
    private String coloum5;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Demo() {
    }

    public Demo(Long id) {
        this.id = id;
    }

    @Generated
    public Demo(Long id, String coloum1, String coloum2, String coloum3, String coloum4, String coloum5) {
        this.id = id;
        this.coloum1 = coloum1;
        this.coloum2 = coloum2;
        this.coloum3 = coloum3;
        this.coloum4 = coloum4;
        this.coloum5 = coloum5;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getColoum1() {
        return coloum1;
    }

    public void setColoum1(String coloum1) {
        this.coloum1 = coloum1;
    }

    public String getColoum2() {
        return coloum2;
    }

    public void setColoum2(String coloum2) {
        this.coloum2 = coloum2;
    }

    public String getColoum3() {
        return coloum3;
    }

    public void setColoum3(String coloum3) {
        this.coloum3 = coloum3;
    }

    public String getColoum4() {
        return coloum4;
    }

    public void setColoum4(String coloum4) {
        this.coloum4 = coloum4;
    }

    public String getColoum5() {
        return coloum5;
    }

    public void setColoum5(String coloum5) {
        this.coloum5 = coloum5;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
